### ISSUE TITLE
Bug report from Valerie

### ISSUE THREAD

**Issue by deannachurch** [deannachurch/assembly_alignment#1]
Hi Deanna:

I ran into an issue with this tonight when I tried to run it with one of the Assemblathon assemblies. Not quite sure what that error means, but it clearly didn't like one of the unitigs. Maybe an issue with name? Any chance you can take a look?

In case you want to try this yourself:
seq report: ftp://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/All/GCA_001297185.1.assembly.txt

Align reports are attached.

Thanks,
Valerie

> > ./assm_align.py --config resources/assm_align_cfg.yml  
> > INFO: ================assm_align.py started: log file=log/assm_align_2016-02-01_2238.log================
> > INFO: Read PacBioCHM1_r2_GenBank_08312015, sequences: 3641, chromosomes: 0
> > INFO: Read GRCh38, sequences: 455, chromosomes: 24
> > INFO: Processing PacBioCHM1_r2_GenBank_08312015
> > INFO: Procssing GRCh38
> > INFO: Writing stats file: /panfs/pan1.be-md.ncbi.nlm.nih.gov/genome_maint/work/CG-3580/GCA_001297185.1_GRCh38/stats/GCA_001297185.1_GRCh38_alignment_stats.txt
> > Traceback (most recent call last):
> >   File "./assm_align.py", line 432, in <module>
> >     main()
> >   File "./assm_align.py", line 376, in main
> >     writeStats(stats1_out, assm1['name'], assm2['name'], assm1_dict)
> >   File "./assm_align.py", line 261, in writeStats
> >     sort_seq_list=sorted(seq_list, key=lambda item: (int(item.partition(' ')[0]) if item[0].isdigit() else float('inf'), item))
> >   File "./assm_align.py", line 261, in <lambda>
> >     sort_seq_list=sorted(seq_list, key=lambda item: (int(item.partition(' ')[0]) if item[0].isdigit() else float('inf'), item))
> > ValueError: invalid literal for int() with base 10: '001041F_p_quiver_quiver'

**Comment by deannachurch** [comment]
Problem was in the alphanumeric sort I set up. This doesn't work will with all assemblies. Put in a try/except to do a regular sort if the alphanumeric fails.
